### PR TITLE
added 3d box selector

### PR DESCRIPTION
**Pull request by hyOzd**
I added a new selector class which allows selecting items inside a given 3D box. I think it will be useful. I can also add some tests if you guys agree with the merge.

### CODE REVIEW

**Comment by jmwright** [comment]
I like it, but hopefully @dcowden will have a chance to comment since he conceived, designed and coded the selector system.

From the code, it looks like objects with portions that fall outside of the box will still be selected as long as their center is inside the box. Is that correct? If so, is that the intent?

Thumbs up from me on moving forward with tests in preparation for a merge.

**Comment by hyOzd** [comment]
>From the code, it looks like objects with portions that fall outside of the box will still be selected as long as their center is inside the box. Is that correct? If so, is that the intent?

Yes, and that was my intent. Is there a way to get the bounding box of an edge/face?

**Comment by dcowden** [comment]
I think this is a great addition! there should be a way to get a bounding
box for an edge/face-- though i cannot recall upfront how to do it....

**Comment by jmwright** [comment]
Here's the bounding box functionality in CQ: https://github.com/dcowden/cadquery/blob/08791e1e31e0e7dabef5cf901eb4be0adc75df67/cadquery/freecad_impl/shapes.py

I'm not implying that there's anything wrong with the way you've done it either. We could just make a note in the wiki that a future improvement might be to allow the user to choose to exclude any objects whose bounding box falls outside of the selection box.

**Comment by dcowden** [comment]
yeah that would work.

**Comment by hyOzd** [comment]
How about this?

Now the question is: which one should be default - bounding box test or center test? I favor the "center" option because it requires a smaller selection box as input, thus it's easier to avoid unwanted items. What do you guys think?

**Comment by jmwright** [comment]
Looks great to me. I could go either way on the default, but I think you make a strong argument for center. My vote is for that.

**Comment by dcowden** [comment]
I agree. I think in practice the center box will be easier to use

**Comment by jmwright** [comment]
I see that the tests have been added. Is this ready to merge?

**Comment by hyOzd** [comment]
Yes, it is.

**Comment by jmwright** [comment]
Thanks!

**Pull request merged**
