### PR TITLE
WIP: Docker cli

### PR DESCRIPTION
**Pull request by dcowden**
This branch builds a docker image, which can execute cadquery scripts with a command line.
It includes all of the dependencies necessary to run cadquery.

A future version will allow starting as a web server that exposes an object build service. to get started:

`   docker run dcowden/cadquery:latest `

Will print out the documentation. Thoughts/comments welcome!
Not ready for merge yet.

### CODE REVIEW

**Comment by fragmuffin** [comment]
@dcowden Very nice!
I'll test it out when I get a chance

**Comment by jmwright** [comment]
@dcowden Using `--format=STEP` doesn't output the result of the script to STEP. I'm not quite sure how to use that option unless the script itself exports to STEP and then dumps that to stdout.
```bash
cat examples/FreeCAD/Ex001_Simple_Block.py | sudo docker run -i dcowden/cadquery:latest --in_spec stdin --out_spec stdout --format STEP > my_object.STEP
```

**Comment by dcowden** [comment]
Can you try adding  'build' word after the image name and before --in_spec
and see if that works?

Step is the default output format so --format step shouldn't be necessary
to get step output.



On Oct 23, 2017 10:00 PM, "Jeremy Wright" <notifications@github.com> wrote:

@dcowden <https://github.com/dcowden> Using --format=STEP doesn't output
the result of the script to STEP. I'm not quite sure how to use that option
unless the script itself exports to STEP and then dumps that to stdout.

cat examples/FreeCAD/Ex001_Simple_Block.py | sudo docker run -i
dcowden/cadquery:latest --in_spec stdin --out_spec stdout --format
STEP > my_object.STEP

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dcowden/cadquery/pull/205#issuecomment-338848855>, or mute
the thread

**Comment by dcowden** [comment]
@jmwright this command worked for me ( from the cadquery project directory):

`cat examples/FreeCAD/Ex001_Simple_Block.py | sudo docker run -i dcowden/cadquery:latest build --in_spec stdin --out_spec stdout`

note the extra 'build' after the image name.  that's reserved for later because additional syntax will include 'runserver' to run a model build service

**Comment by jmwright** [comment]
@dcowden Ok, that output a file that looks like it's in STEP format, but FreeCAD gives an error when I try to open it. stdout is redirected, so I get this at the top of the file.
```bash
Launching python with arguments --in_spec stdin --out_spec stdout --format STEP
```
If I remove that line from the top and re-save the STEP file, it opens fine.

**Comment by dcowden** [comment]
oh poop, i added that in in a fit of debugging at the end-- that's an easy fix-- i'll do that ASAP.

As a side note, if you look at this PR, you'll see i had to write a custom context manager and add it into the cq export code and init code, because FreeCAD clutters stdout with stuff when it exports STEP, and when it even loads.

**Comment by jmwright** [comment]
> As a side note, if you look at this PR, you'll see i had to write a custom context manager and add it into the cq export code and init code, because FreeCAD clutters stdout with stuff when it exports STEP, and when it even loads.

Thanks. I'll keep that in mind while figuring out how to rework the model build environment code for CQFM.

**Comment by jmwright** [comment]
1. There's no way to specify a CQ script file to run using an option, and so the script text has to be piped in. Was that an intentional choice? Could cat-ing the script in cause problems with tabs and spaces in some cases?

2. How does the `--help` option work? I can't seem to get it to display any help message. I'm probably just doing it wrong.

```bash
docker run -i dcowden/cadquery:latest --help
```

3. What format does the parameters JSON file need to be in? The following doesn't seem to work.
```json
{
"length": 60.0,
"height": 60.0,
"thickness": 60.0
}
```
Here's how I used the params option:
```bash
cat cadquery-freecad-module/Libs/cadquery/examples/FreeCAD/Ex001_Simple_Block.py | sudo docker run -i dcowden/cadquery:latest build --in_spec stdin --out_spec stdout --params cq_params.json --format STEP > my_object.STEP
```

**Comment by dcowden** [comment]
@jmwright
With docker, the image doesnt have ability to see files in your local filesystem unless you mount them as a volume using -v.  

In_spec must be a file spec that the container can see.  You can use local filesystem for in_spec and out_spec if you use -v to mount some local files into the container.  

The format for your parameters is right, but it expects the json as a string argument, not a filename. This allows using parameters without using -v.

You can also read parameters from a file using --param_file, but the file must be mounted in the container.

To print help, just run the container with no arguments are all

**Comment by jmwright** [comment]
I've put the container through it's paces, including mounting a host directory for a JSON parameters file, the input script file, and the output file. I can't think of any other things to try.

**Comment by dcowden** [comment]
First version

**Pull request merged**
