### PR TITLE
Implement CI on Windows

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Seems to be working fine. Only thing left is to setup CI on this repo

### CODE REVIEW

**Comment by dcowden** [comment]
@adam-urbanczyk is that something we'd prefer done with my account?

**Comment by adam-urbanczyk** [comment]
@dcowden  I am trying something via the account of @jmwright on appveyor. Let's see how it goes

**Comment by dcowden** [comment]
@adam-urbanczyk it looks like since Github doesnt have an appveyor service, we probably need to register a webhook to trigger builds?

**Comment by dcowden** [comment]
Will do!

**Comment by dcowden** [comment]
done-- added for both pull request and push.

**Comment by adam-urbanczyk** [comment]
Thanks, it works! The coverage decrease is due to Windows specific code (cf. #247).

**Comment by dcowden** [comment]
Merging this, thanks for setting it up!

**Comment by adam-urbanczyk** [comment]
For future reference this PR was solving #246

**Pull request merged**
