### PR TITLE
Improve unicode support

### PR DESCRIPTION
**Pull request by galou**
Ex029_Braille.py now works again.
Prepare for Python 3.
All test pass except testAMF, where, I suppose, the test fails because of lacking of support in xml.etree.

### CODE REVIEW

**Comment by dcowden** [comment]
thank you @galou for this contribution!! Much appreciated!

**Comment by galou** [comment]
Also changed the text of `Ex029_Braille.py` from `FreeCAD` to `CadQuery`. Everybody would have noticed by himself, I guess :smile:.

**Comment by jmwright** [comment]
@adam-urbanczyk Other than the example changes, has this PR been addressed now?

**Comment by jmwright** [comment]
@galou Now that #224 has been merged there are a couple of conflicts with this PR (exports.py and TestExporters.py). I think that the intent of your changes to those files has been addressed in #224. Would it be possible for you to pull master into your branch and resolve those conflicts so that we can merge this?

**Comment by jmwright** [comment]
@galou If you're not already working on this, I think I'll try to merge the changes manually within the next week. I appreciate your contributions, and want to make sure they get pulled in.

**Comment by jmwright** [comment]
The changes to the braille example have been integrated into master in commit 22fabda8d8de63ae19d82e34934c29b5f29940c1

**Comment by jmwright** [comment]
@galou Your changes (with some necessary modifications to resolve conflicts) have been pulled into master in commit 5c7553870294d94ba2e596d79180ce1051cebab7

Sorry about the mess on this. In the push for Python 3 compatibility we ended up with PRs that overlapped yours. I'm going to go ahead and close this since the content of the PR has been pulled in another way. 

Thank you for these contributions.

**Comment by galou** [comment]
Everything look to work as it should, thanks for the integration!

**Pull request closed without merging**
