### PR TITLE
amf xml bugfix

### PR DESCRIPTION
**Pull request by fragmuffin**
I've been having trouble with the `cadquery` tests for a while now, like many Python 2/3 issues this one boils down to a `unicode` / `str` missmatch.

**Question:**
Does the AMF XML header need to explicitly state that it's unicode?

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
What is the bug? CI seems to be fine, or am I missing something?

On Jan 17, 2018 4:09 AM, "Peter Boin" <notifications@github.com> wrote:

I've been having trouble with the cadquery tests for a while now, like many
Python 2/3 issues this one boils down to a unicode / str missmatch.

*Question:*
Does the AMF XML header need to explicitly state that it's unicode?
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/dcowden/cadquery/pull/218
Commit Summary

   - defaulted AMF XML ouput encoding
   - file descriptor assumption

File Changes

   - *M* cadquery/freecad_impl/exporters.py
   <https://github.com/dcowden/cadquery/pull/218/files#diff-0> (4)
   - *M* tests/TestExporters.py
   <https://github.com/dcowden/cadquery/pull/218/files#diff-1> (27)

Patch Links:

   - https://github.com/dcowden/cadquery/pull/218.patch
   - https://github.com/dcowden/cadquery/pull/218.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dcowden/cadquery/pull/218>, or mute the thread

**Comment by fragmuffin** [comment]
@adam-urbanczyk 
If I switch back to the current `master`, I get:

```
(cadquery) ~/prj/cadquery (master) $ ./runtests.py 
..............................................................................................................................................................EEE....No handlers could be found for logger "test"
.......
======================================================================
ERROR: testAMF (tests.TestExporters.TestExporters)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nymphii/prj/cadquery/tests/TestExporters.py", line 37, in testAMF
    self._exportBox(exporters.ExportTypes.AMF,['<amf units','</object>'])
  File "/home/nymphii/prj/cadquery/tests/TestExporters.py", line 22, in _exportBox
    exporters.exportShape(p,eType,s,0.1)
  File "/home/nymphii/prj/cadquery/cadquery/freecad_impl/exporters.py", line 72, in exportShape
    aw = AmfWriter(tess).writeAmf(fileLike)
  File "/home/nymphii/prj/cadquery/cadquery/freecad_impl/exporters.py", line 164, in writeAmf
    ET.ElementTree(amf).write(outFile,encoding="unicode",xml_declaration=True)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 817, in write
    self._root, encoding, default_namespace
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 884, in _namespaces
    add_qname(tag)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 868, in add_qname
    qnames[qname] = encode(qname)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 843, in encode
    return text.encode(encoding)
LookupError: unknown encoding: unicode

======================================================================
ERROR: testSTEP (tests.TestExporters.TestExporters)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nymphii/prj/cadquery/tests/TestExporters.py", line 40, in testSTEP
    self._exportBox(exporters.ExportTypes.STEP,['FILE_SCHEMA'])
  File "/home/nymphii/prj/cadquery/tests/TestExporters.py", line 22, in _exportBox
    exporters.exportShape(p,eType,s,0.1)
  File "/home/nymphii/prj/cadquery/cadquery/freecad_impl/exporters.py", line 92, in exportShape
    fileLike.write(res)
TypeError: unicode argument expected, got 'str'

======================================================================
ERROR: testSTL (tests.TestExporters.TestExporters)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nymphii/prj/cadquery/tests/TestExporters.py", line 31, in testSTL
    self._exportBox(exporters.ExportTypes.STL,['facet normal'])
  File "/home/nymphii/prj/cadquery/tests/TestExporters.py", line 22, in _exportBox
    exporters.exportShape(p,eType,s,0.1)
  File "/home/nymphii/prj/cadquery/cadquery/freecad_impl/exporters.py", line 92, in exportShape
    fileLike.write(res)
TypeError: unicode argument expected, got 'str'

----------------------------------------------------------------------
Ran 172 tests in 5.833s

FAILED (errors=3)
...
Reading STEP file......
```

The changes in this PR corrects these errors on my setup.

* `STL` : the test is changed
* `STEP` : the test is changed
* `AMF` : `ET.ElementTree` call changed to not explicitly set an `ecoding` type (hence the question)

**Comment by dcowden** [comment]
What is the next step on this one?

**Comment by fragmuffin** [comment]
@adam-urbanczyk you originally changed the encoding type to `unicode` from `ISO-8859-1` in fa131d7.
does the encoding need to be explicitly set?... if so, would you prefer I found a solution that enabled the `ET.ElementTree.write` command to keep its encoding type?

@dcowden @adam-urbanczyk : does this branch pass unit-testing on your systems?
(I'm running python `2.7.12` on ubuntu)

**Comment by adam-urbanczyk** [comment]
@fragmuffin I did that to make python3 work. I still do not get why CI does not see the problem. Anyhow, I'll check your branch on py2 and py3. But ultimately would be nice to understand what is going on.

**Comment by adam-urbanczyk** [comment]
Actually CI does see the issue: https://travis-ci.org/dcowden/cadquery/builds/323825432#L1724

**Comment by fragmuffin** [comment]
Well, after poking Travis to re-run CI, it looks like this branch is passing.
Does anyone see any problem with this change?

**Root Cause**
It looks like `ElementTree` isn't equip to distinguish the difference between _encoding_ and _decoding_ a string; `'abc'.encode('unicode')` raises an exception, while `'abc'.decode() == u'abc'`.

**Comment by adam-urbanczyk** [comment]
Let me still check it on py3.

**Comment by adam-urbanczyk** [comment]
Sorry, but I see many more failures now on py3. Could we maybe reconsider the solution space?

```
======================================================================
ERROR: testSTEP (tests.TestExporters.TestExporters)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/basia/cq2/cadquery/tests/TestExporters.py", line 65, in testSTEP
    self._exportBox(exporters.ExportTypes.STEP,['FILE_SCHEMA'])
  File "/home/basia/cq2/cadquery/tests/TestExporters.py", line 47, in _exportBox
    exporters.exportShape(p,eType,s,0.1)
  File "/home/basia/cq2/cadquery/cadquery/freecad_impl/exporters.py", line 92, in exportShape
    fileLike.write(res)
  File "/home/basia/cq2/cadquery/tests/TestExporters.py", line 34, in write
    return super(TestStringIO, self).write(unicode(content))
NameError: name 'unicode' is not defined

======================================================================
ERROR: testSTL (tests.TestExporters.TestExporters)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/basia/cq2/cadquery/tests/TestExporters.py", line 56, in testSTL
    self._exportBox(exporters.ExportTypes.STL,['facet normal'])
  File "/home/basia/cq2/cadquery/tests/TestExporters.py", line 47, in _exportBox
    exporters.exportShape(p,eType,s,0.1)
  File "/home/basia/cq2/cadquery/cadquery/freecad_impl/exporters.py", line 92, in exportShape
    fileLike.write(res)
  File "/home/basia/cq2/cadquery/tests/TestExporters.py", line 34, in write
    return super(TestStringIO, self).write(unicode(content))
NameError: name 'unicode' is not defined

======================================================================
ERROR: testSVG (tests.TestExporters.TestExporters)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/basia/cq2/cadquery/tests/TestExporters.py", line 59, in testSVG
    self._exportBox(exporters.ExportTypes.SVG,['<svg','<g transform'])
  File "/home/basia/cq2/cadquery/tests/TestExporters.py", line 47, in _exportBox
    exporters.exportShape(p,eType,s,0.1)
  File "/home/basia/cq2/cadquery/cadquery/freecad_impl/exporters.py", line 69, in exportShape
    fileLike.write(getSVG(shape.wrapped))
  File "/home/basia/cq2/cadquery/tests/TestExporters.py", line 34, in write
    return super(TestStringIO, self).write(unicode(content))
NameError: name 'unicode' is not defined

======================================================================
ERROR: testTJS (tests.TestExporters.TestExporters)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/basia/cq2/cadquery/tests/TestExporters.py", line 68, in testTJS
    self._exportBox(exporters.ExportTypes.TJS,['vertices','formatVersion','faces'])
  File "/home/basia/cq2/cadquery/tests/TestExporters.py", line 47, in _exportBox
    exporters.exportShape(p,eType,s,0.1)
  File "/home/basia/cq2/cadquery/cadquery/freecad_impl/exporters.py", line 67, in exportShape
    fileLike.write( mesher.toJson())
  File "/home/basia/cq2/cadquery/tests/TestExporters.py", line 34, in write
    return super(TestStringIO, self).write(unicode(content))
NameError: name 'unicode' is not defined

======================================================================
FAIL: test_setting_boolean_variable (tests.TestCQGI.TestCQGI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/basia/cq2/cadquery/tests/TestCQGI.py", line 189, in test_setting_boolean_variable
    self.assertTrue(result.success)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 172 tests in 8.206s

FAILED (failures=1, errors=9)
```

**Comment by adam-urbanczyk** [comment]
I think I found few things:

* remove all explicit `str` calls and replace with `'{}'.format`
* use `io.BytesIO` for ET based export
* adapt test to work with BytesIO and StringIO object (again the format trick)

I'll try to put this together into a PR.

**Comment by fragmuffin** [comment]
@adam-urbanczyk how are you testing with py3?
If I can test on both platforms locally, then I should be able to sort this straight away.

Also, if the changes being committed to `main` are to be both py2 and py3 compliant, then can we get CI to test both environments?

**Comment by fragmuffin** [comment]
oh!, I just saw #220

**Comment by adam-urbanczyk** [comment]
@fragmuffin I propose to first fix #220 (merge #223 once it is ready), then come back to your PR.

**Comment by fragmuffin** [comment]
Sounds good @adam-urbanczyk :+1:

**Comment by jmwright** [comment]
@fragmuffin @adam-urbanczyk @dcowden Drawing attention to this PR having conflicts now after the changes in #223

**Comment by adam-urbanczyk** [comment]
@jmwright  I think this is solved now. The only failing test is on py3 and cqgi. I do not understand the intent of it BTW

**Comment by jmwright** [comment]
@adam-urbanczyk So I can close this PR without merging?

I have a task to take a look at the CQGI errors in Py3. I'll make that a priority now that I have a way to make sure I'm not breaking Py2 support in the process.

**Comment by adam-urbanczyk** [comment]
@jmwright  yes please close. Would be great if you could solve the CQGI test.

**Comment by dcowden** [comment]
Thanks so much guys for diving into this! It's such a huge deal to have everything working in py3 and py2!

**Comment by fragmuffin** [comment]
Yeah! Thank you @adam-urbanczyk !

**Pull request closed without merging**
