### PR TITLE
Added codecov

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
It looks like codecov merges coverages nicely. Would you agree to at least add it to coveralls?

### CODE REVIEW

**Comment by jmwright** [comment]
@adam-urbanczyk Does something need to be done on the Coveralls website account, or will merging this PR take care of everything?

**Comment by adam-urbanczyk** [comment]
@jmwright  one needs to add this project to codecov (no special configuration needed)
@dcowden  did you by any chance already do that?

**Comment by dcowden** [comment]
@adam-urbanczyk I didnt add this project to codecov. Is this ready to merge?

@jpmlt  when this is merged, can you pull master onto your branch and re-push? I think it will allow your sweep feature to pass the builds also.

**Comment by adam-urbanczyk** [comment]
Yes, it is ready.

**Comment by jmwright** [comment]
Why is the Appveyor version 1.0.x instead of the CadQuery version of 1.1.x? Is there some significance to that?

**Comment by jmwright** [comment]
@adam-urbanczyk in all the AppVeyorBot posts on this issue.

**Comment by adam-urbanczyk** [comment]
I think this is just build numbering convention (not sure what is the rationale though): https://ci.appveyor.com/project/jmwright/cadquery/history

In the log I see this (1.1.0):
https://ci.appveyor.com/project/jmwright/cadquery/build/1.0.11#L313

**Pull request merged**
