### PR TITLE
Add the named planes ZX YX ZY

### PR DESCRIPTION
**Pull request by galou**
Should I write a unit test for this? Where?

### CODE REVIEW

**Comment by jmwright** [comment]
Sorry for the slow reply. I would roll your tests in with the existing
selector tests.

https://github.com/dcowden/cadquery/blob/3503f7bfafb03c69d7b99d9819f914b32249de09/tests/TestCQSelectors.py#L4

Jeremy

**Comment by galou** [comment]
I wrote simple unit tests.
On the way, I modified the Plane.XY() functions and similar. This compelled me to do more changes then. Are such changes are OK for you?

**Comment by jmwright** [comment]
These changes look good to me. @dcowden do you have time to weigh in before I merge?

**Comment by jmwright** [comment]
Thanks for contributing @galou !

**Pull request merged**
