### PR TITLE
Add mirroring operation for 3D CQ object and add tessellate(0.1) in the BoundBox function

### PR DESCRIPTION
**Pull request by huskier**
1. Add a mirror function into CQ class(wrap) and Shape class(implement); 
 2. To get precise BoundBox, add tessellate(0.000001) in the BoundBox function implement.

Thanks for reviewing the pull request!

### CODE REVIEW

**Comment by dcowden** [comment]
are there any tests that go with this behavior? 
for the mirror functionality, an addition to doc/examples.rst would be great-- that would allow an easy way to visually confirm that the mirror works, and provide, at the same time, an example of how to use it. 

a test case for the tessellate function might be good as well. that woud probably belong in tests/TestCadQuery.py

**Comment by huskier** [comment]
@dcowden Yes, I test the mirror functionality myself. Following your suggestion, I will work on the example and test things.

For the BoundingBox function:
Do we need to pass a precision parameter into the BoundingBox function?

**Comment by dcowden** [comment]
That's a good question. It is not intuitive that bounding box needs a
precision,  but on the other hand using a hard coded, very small value
might be very computationally expensive, and that could be surprising too.

For example,  how long does it take to tessellate a sphere to tolerance
0.000001?

I think we should probably add a tolerance parameter, and default the value
to a number more like 0.001.

My rationale for that number is that it is the largest power of ten that
would still be considered 'small' when the model unit of measure is inches
or mm or cm, which are the most common units

We should use a larger default precision if it turns out that even that
value is costly for curved surfaces.

**Comment by huskier** [comment]
@dcowden 
I add a mirroring example into doc/example.rst, and also add a test function testBoundingBox into tests/TestCadQuery.py file. For the tolerance of BoundingBox, it is very slow to compile the docs with sphinx-build when I set the it to 0.001, so I default it to 0.1 at present.

Thank you for your reviewing!

**Comment by dcowden** [comment]
Thanks for adding the test and the documentation! 
And thanks for the contribution!

**Pull request merged**
