### PR TITLE
adds vector input for box

### PR DESCRIPTION
**Pull request by burdickjp**
allows dimensions of box to be a vector.

### CODE REVIEW

**Comment by dcowden** [comment]
Hey, Jeffrey:

Thanks for contributing this change!  Looks like the tests are failing after this change, so i cannot merge it. The error was:

  File "./runtests.py", line 2, in <module>
    from tests import *
  File "/home/travis/build/dcowden/cadquery/tests/__init__.py", line 1, in <module>
    from cadquery import *
  File "/home/travis/build/dcowden/cadquery/cadquery/__init__.py", line 11, in <module>
    from .cq import *
  File "/home/travis/build/dcowden/cadquery/cadquery/cq.py", line 2321
    def box(self, vector=None, length, width, height, centered=(True, True, True), combine=True, clean=True):
**SyntaxError: non-default argument follows default argument
**

after you make a change locally, make sure to run python runtests.py from the root of the project before you update the PR, that way you know the tests will pass.

**Comment by burdickjp** [comment]
This passed tests and, I think, will function much better.

**Comment by dcowden** [comment]
Can you please add a test case for this functionality also?

It is a little odd to support a vector for length, and then ignore the other two variables ( width and height).  What would we do if the user attempted to pass in box((1,2,3),(4,5,6),10) ?

I feel like a better way to do this would be to declare another version of the box method, and then delegate its implementation to the current one. 

for example:

 def box(self, vector, centered=(True, True, True), combine=True, clean=True):
     return box(self, vector[0], vector[1], vector[2], centered, combine, clean )

This would be much cleaner, I think.  

Also please add a test case to this file:
https://github.com/dcowden/cadquery/blob/master/tests/TestCadQuery.py

**Comment by burdickjp** [comment]
My intention was to be able to call box with just a tuple or list:
dims = [1,2,3]
box(dims)
while still being able to call box the other way:
dimX, dimY, dimZ = 1,2,3
box(dimX, dimY, dimZ)

The behaviour I would expect for a user trying to pass box((1,2,3),(4,5,6),10) would be an error. Am I right in thinking this, or is there something I am not seeing?

**Comment by dcowden** [comment]
I _think_ your code wouldn't result in an error if the user passes a vector
for length and width, though. It appears that the code will accept a vector
as a the first argument, but then if the first arg is a vector, the other
two arguments are overwritten(ignored).

I think it is better to make an overloaded function. you can still achieve
the result you are after-- either form will work. But what's going on is
much clearer ( IMO), using two separate method declarations.

**Comment by burdickjp** [comment]
I'm sorry, I was rather ambiguous in my statement. I was saying I think it **should** return an error, not that it currently does. I'm not yet familiar with how to make Python return an error.

I'm a bit confused on having two defs with the same name, or are you suggesting having a boxVector def which calls the box def? That makes some sense, and sounds easy as hell, but would muddy the waters some, yes?

**Comment by dcowden** [comment]
Yes, two methods where the new one is delegating to the old one is what I'm
suggesting. It doesn't muddy the waters, it clears it. Two methods makes it
more clear that there are two ways to call the method. The extra signature
will also make it much better to handle indeterminism. In particular, you
simple cannot pass in height and width, And then have them be ignored
without your knowledge, which is a possibility in your proposed version

**Comment by dcowden** [comment]
Per some out of band conversations, I still recommend having overloaded methods here, rather than having logic in the same function that accepts multiple types for the first argument, and then ignores the values of the other two when the first arg is a vector.

**Comment by jmwright** [comment]
@dcowden @burdickjp Where does this PR stand? Is it ready to be merged?

**Comment by dcowden** [comment]
It is not ready to be merged. I would rather see an overloaded method than
the current approach. AFAIK the modifications have not been made yet to
change strategies. I've been assuming ( perhaps incorrectly that @burkickjp
would make those changes.

**Comment by burdickjp** [comment]
I apologize. I've been thinking about this a bit while using cadquery on a hardware design I'm working on: https://github.com/LibreMatter/openVise/tree/cadQuery?files=1

The difficulty I'm seeing is that there are other classes in cadquery which use dimensional inputs with separate variables. I think consistency is very important. Having a separate class for vector inputs for each of them doesn't seem like the right answer to me.

**Comment by dcowden** [comment]
No worries on the delays! None of us are getting paid enough to worry about that :)

I'm not proposing a separate class, just a separate method.

**Pull request closed without merging**
