### PR TITLE
Inheritance Friendly Fixes

### PR DESCRIPTION
**Pull request by fragmuffin**
A few fixes for inheritance based issues:

In the original code:

```python
>>> import cadquery
>>> class MyCoordSystem(cadquery.Plane):
...     pass
>>> cs = MyCoordSystem((0,0,0),(1,0,0),(0,0,1))
>>> type(cs.rotated((0,0,0)))
cadquery.freecad_impl.geom.Plane
```

so the returned object's type is downgraded to `Plane`

with the change to `cadquery.Plane.rotated`:

```python
>>> type(cs.rotated((0,0,0)))
__main__.MyCoordSystem
```

I found a few other potential inheritance bugs waiting to happen, but this should fix them.

### CODE REVIEW

**Comment by jmwright** [comment]
@fragmuffin The Python 3 tests failed with a segfault. I've been having that problem and just restarting the job fixes it, so that's what I did.

**Comment by jmwright** [comment]
Well, that doesn't seem to be fixing it this time.

**Comment by fragmuffin** [comment]
Oh weird, I'll try running the tests locally tomorrow.

**Comment by fragmuffin** [comment]
@jmwright @adam-urbanczyk 
I've just spend the last few hours playing with `Dockerfile` and `docker-compose.yml` configurations so I can:

```bash
docker-compose build test_py2
docker-compose run test_py2
```

And then the same for py3. I'll share a gist when it's working....
But that work aside, how do you recommend testing py3 functionality?
If I can get these docker containers set up, I'm open to suggestions on how (or if) it's introduced to cadquery

**Comment by fragmuffin** [comment]
agh!, this is driving me crazy!

**Python 2.x**
I can run most tests, but for some reason it's only running ~100 of them and I can't see `stdout` for it to tell me why.

**Python 3.x**
I can't install `freecad-daily` on a debian system, which is what the python containers are based on.
`conda install freecad=0.17` can't find a freecad package, but I'm following what TravisCI is doing...

I should probably get some sleep

**Comment by adam-urbanczyk** [comment]
You need to use the FreeCAD channel for conda. I'll elaborate later...

**Comment by adam-urbanczyk** [comment]
@fragmuffin  I missed that you figured it out in the end.

@jmwright  Any clue why is this segfaulting? Should I check with the maintainer of the conda package? Or maybe we should build our own freecad? It used to work fine, so first guess is that the last version (from 3 days and 23 hours ago according to this page: https://anaconda.org/freecad/freecad/files) is giving us trouble.

**Comment by jmwright** [comment]
@adam-urbanczyk I suspect that they've pulled a broken version of FreeCAD for the conda package, but I don't have any proof of that. FreeCAD 0.17 is in feature-freeze according to Yorik so no new features are being added, but it's still under heavy development to get it ready for release.

I think it's worth trying to contact the conda package maintainer. If we don't get a response, we may be forced to build our own Python 3 FreeCAD package, even if it's only temporarily.

**Comment by fragmuffin** [comment]
Thanks @adam-urbanczyk I haven't used `conda` before, so I had some learning to do.

I've got it mostly working:
https://gist.github.com/fragmuffin/a0cc76606a51910b3be12435801ca416
although it's still only running ~1/2 the tests

I'm seeing the segfault locally now, I agree with @adam-urbanczyk; probably a dailybuild issue, but I haven't confirmed that.

I'm inclined to re-design the docker containers basing them on an `ubuntu` image, instead of a `debian` one. This way `freecad` can be installed using `apt` on both py2 and py3, making their setup procedure almost identical, which should eliminate some potential issues in testing.

**Comment by jmwright** [comment]
And thanks for the contribution @fragmuffin

**Comment by fragmuffin** [comment]
my pleasure @jmwright

**Pull request merged**
