### PR TITLE
Look for Python syntax errors and undefined names

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by jmwright** [comment]
@cclauss Thanks for the contribution! With the way the CadQuery Gateway Interface (CQGI) works, the show_object function will always show as undefined. It's not explicitly imported.Is there a way to exclude that?

**Comment by dcowden** [comment]
In light of other discussion ongoing, Im open to changing cqgi so an import is required.

**Comment by cclauss** [comment]
Explicit is better that implicit.

**Comment by dcowden** [comment]
@cclauss +1

**Pull request closed without merging**
