### PR TITLE
added options to build method

### PR DESCRIPTION
**Pull request by dcowden**
Jeremy: this adds a dictionary to the build method. Turns out, the debug method already worked this way, so this way they work the same.

I think this will solve your need to add color and transparency.  if you like it, feel free to merge, or let me know if you'd like some other functionality

### CODE REVIEW

**Comment by jmwright** [comment]
@dcowden Got a little time this morning to try this out.

When I make this call:
```python
 build_result = cqModel.build(build_parameters=build_parameters)
```
Then iterate over the results:
```python
for result in build_result.results:
```

It seems like each `result` is still a Workplane object. Any ideas what I'm doing wrong? It looks like the build function may still be putting shapes in `results` instead of `BuildResult` objects, but I'm not sure if I'm understanding how things are supposed to work.

**Comment by dcowden** [comment]
I'll have a look. I thought that was covered with the unit tests, but I
will check what's going on.

**Comment by dcowden** [comment]
I had a look  and I have to admit i'm a bit mystified. This behavior is definitely covered in the tests, and looking at the code it should be working.

This test in particular should cover it:
https://github.com/dcowden/cadquery/blob/cqgi_options/tests/TestCQGI.py#L65

Test failed before I changed it, so i know the behavior changed in this case at least.  

I didnt merge this into master yet, in case you're using master version still

**Comment by jmwright** [comment]
I'm using your cqgi_options branch, and I've verified that I copied it correctly into the CQFM file structure. I'll take another look as soon as I get a chance.

**Comment by dcowden** [comment]
i'm still looking also.  It could be something really silly but i can't see
it.

**Comment by jmwright** [comment]
I'm AFK now, but when I was testing it I tried `result.options` and `result.shape.options` and got an error about the Workplane object not having member `options` or `shape`.

**Comment by dcowden** [comment]
very strange. the only thing i saw in your code that caught my eye vs the
tests is that you're passing in build parameters, and the unit tests are
not. but that shouldn't make a difference.

can you add a line of code that throws an exception here:
https://github.com/dcowden/cadquery/blob/cqgi_options/cadquery/cqgi.py#L303

that will prove that we're using the version of cq you're looking at.

**Comment by jmwright** [comment]
The problem ended up being that I had cadquery installed via pip as well. Apparently the pip version takes precedence over the copy embedded with CQFM.

The following line will render a model with transparency.
```python
build_object(result, options={"rgba": (204, 204, 204, 0.8)})
```

I'll go ahead and merge this. Thanks.

**Comment by dcowden** [comment]
at that makes sense!

i think the options dictionary worked well--i'd have had no idea at all how
you want to represent it, and this made it pretty easy.

**Pull request merged**
