### PR TITLE
added intersect() to Workplane

### PR DESCRIPTION
**Pull request by fragmuffin**
addressing issue #188

### CODE REVIEW

**Comment by dcowden** [comment]
Thanks for the contribution!

**Comment by fragmuffin** [comment]
@dcowden 
what's the plan for the next (iterative) `cadquery` release?
would you like to synchronise it with the initial release of my `cqparts` lib?

I need to spend some more time on another project over the next few weeks, but I would like to have an alpha release of `cqparts` by the end of October

**Comment by dcowden** [comment]
@fragmuffin not sure there is a plan for release of the 1.x stream, but it is definitely time. Your parts library is awesome

Do you prefer to keep your library separate from cq, or would you be interested in bundling your code with cq?

**Comment by fragmuffin** [comment]
@dcowden I feel like the overlap between `cadquery` and `cqparts` is minimal, which is an argument to keep them separate.
Of course `cqparts` has a huge dependency on `cadquery` (hence the `cq` prefix), but `cadquery` can stand alone without parts.
There's a simplicity to that I like. So I think I'd prefer to keep it separate.

Do you feel strongly about merging them?

**Comment by dcowden** [comment]
@fragmuffin, no definitely not, I just wanted to offer. Coordinated releases is fine with me. It would probably be easiest for users if we adopt common numbering.

@jmwright are you ready to do a call 1.x release soon?

**Comment by fragmuffin** [comment]
Thank you very much for your consideration @dcowden , that means a lot to me.
But yes; I would like to keep it separate 😃

**Comment by jmwright** [comment]
>  are you ready to do a call 1.x release soon?

We could release v1.1.0 any time. I was hoping to address issue #186 before the release, but I'm not sure I'm going to get to it.

**Comment by fragmuffin** [comment]
@jmwright well I'm in no rush.

out of curiosity, what's your release process?

I ask because I set up a semi-automated deployment for another PyPI package I wrote.
https://github.com/fragmuffin/pygcode/tree/master/deployment
Using this I can do a full test, sandbox deployment, test from sandbox, deploy to production, test from prod, all on py2 and py3. and I can do all of that in about 10min, with complete confidence.

would you be interested in something similar for `cadquery`?
I can easily put together a PR

**Comment by jmwright** [comment]
> out of curiosity, what's your release process?

When we tag a release Travis will push it to PyPi. When we commit there's standard automated testing and coverage checks, but that's as far as it goes. The more we can automate our testing and release process the better in my mind. @dcowden understands how CI fits with CQ a lot better than I do though.

**Pull request merged**
