### PR TITLE
First try to support python3 testing in CI

### LINKED ISSUE #220: CI on both python 2 .7 and python 3.6
This is critical if we want to move towards python3 being fully supported.

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Will eventually fix #220 , do not merge yet

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@dcowden  @jmwright  could you review this? Builds now run in parallel on py3.6/conda and py2.7. Tests fail so CI indicates a failure, so now we have more motivation to fix them : ) .

**Comment by dcowden** [comment]
Thanks for all the work Adam! I'll review this weekend.

**Comment by dcowden** [comment]
@adam-urbanczyk i love introduction of matrix tests for python 2 and 3.  
I don't want master to be broken, so we shouldnt merge this until it passes.  If master is broken, the documentation and examples will be broken too.

 If you want, we could make a python_3_support branch, and merge this onto that branch. Or, if you prefer we can keep working on your fork.

Does the conda create command upload the package to their repo and all that, or does it just produce an artifact?  If it makes just an artifact, do you know how we'll make it available for users to download?

**Comment by adam-urbanczyk** [comment]
@dcowden  the thing is that currently master is broken, you just don see it (cf this commit https://github.com/dcowden/cadquery/pull/223/commits/494b218f18d2a28eb1d159957ee3ad4fdd763c40 and travis logs for 2.7 and old .travis.yml). I think this is the real problem. Based on this PR we get a real picture of what is working and what is not. 

On the documentation: why would you upload documentation of a broken branch? If you insist this can be moved to `after_script`.

My view on the python3 compatibility is: we are 4 failing tests away, so should be ready within a weak. If you don't enable the testing now it will be always a moving target (i.e. how will you now that your new commit does not break it). 

For now I do not create a conda package, could be possible obviously. `conda create` is for an environment

**Comment by dcowden** [comment]
@adam-urbanczyk I suppose being broken for a week isnt a big deal, so if its easier to work on master that's ok with me. That said, I'm still not understanding why we can't work on a branch that has your changes-- the builds will fail on the branch, and we know we're good to go when they pass, and then we can merge it in.

I understand the sentiment that the current product is broken-- but silent failures aside the current build produces a working 2.7 version with documentation that is accurate ([here](http://dcowden.github.io/cadquery/)). 

Is it difficult in a way i dont understand to merge this onto a branch and then develop on that till all is well?

**Comment by adam-urbanczyk** [comment]
@dcowden does this setup is OK with you (deploy docs in after_script)? Note that I did not change any functional code, I think we need to be honest about the failures otherwise (red badge and all that).

I am proposing this to circumvent regression from other PRs in terms of python2 and python3 compatibility.

**Comment by dcowden** [comment]
I'm ok with this approach, given that we're pretty close to being back to green.
@jmwright your thoughts?

**Comment by jmwright** [comment]
@dcowden I'm good with what Adam is suggesting.

**Comment by jmwright** [comment]
Are we going to merge the other, related PRs before fixing the errors?

**Comment by dcowden** [comment]
ok, i think we're agreed then! @adam-urbanczyk are we ready to merge this then?

**Comment by adam-urbanczyk** [comment]
@dcowden  @jmwright  actaully I fixed quite some tests (py2 should be all green). Can be merged now.

**Pull request merged**
