### PR TITLE
Fixed usage of toWorldCoordinates in move and moveTo

### PR DESCRIPTION
**Pull request by xix-xeaon**
Hey, I encountered this bug while checking out your project and thought I might fix it. This is my first time ever doing this so I hope I've done it decently. Anyway, I don't see many commits lately - I hope this project doesn't die since it seems like a promising replacement for openscad.

### CODE REVIEW

**Comment by jmwright** [comment]
Thanks for contributing @xix-xeaon . Could you please give the steps to replicate the bug you were seeing?

CadQuery is far from dead. @dcowden is very busy right now, and I've been busy using CQ for a couple of projects. If you haven't already, you might want to check out the CQ module for FreeCAD. It provides a handy CQ GUI. https://github.com/jmwright/cadquery-freecad-module

**Comment by dcowden** [comment]
@jeremy thanks for weighing in!

**Comment by xix-xeaon** [comment]
Ah, well when I called moveTo I got
```
Traceback (most recent call last):
  File "./tic-tac-toe.py", line 21, in <module>
    r = r.moveTo(x*(piece+width),y*(piece+width)).rect(piece,piece)
  File "/usr/local/lib/python2.7/dist-packages/cadquery/CQ.py", line 1112, in moveTo
    return self.newObject([self.plane.toWorldCoordinates(newCenter)])
AttributeError: Plane instance has no attribute 'toWorldCoordinates'
```
I didn't find `toWorldCoordinates` but I did find `toWorldCoords` so I changed it, but it doesn't take a `Vector` argument, only tuple, which it uses to make a Vector, so I just changed it to use a Vector if one was passed. Now moveTo does what I expected it to do and I get no error.

Also, before I made it handle the vector I got an error on `Vector.__len__`, it expects two arguments but only gets one. I'm not sure when __len__ would receive more arguments than its instance but in the Vector class __len__ has been defined twice, first normally and then also taking an `other` argument. The second definition overwrites the first so I'm not sure what the intention here is (and I don't know what other is for), but I'd assume it should only be defined once with the code something like
```
    def __len__(self, other=None):
        if other is None:
            return self.Length
        return self.wrapped.__len__(other)
```

BTW, thanks for responding so quickly. Yes, I tried CQ through FreeCAD first but we don't really get along. I found it easier to just open the stl in MeshLab and reload the file after I run my CQ script. However, having tested it for a bit now, I find it very difficult to grasp how CQ actually works and how I can use it to make my designs. Which functions create things and which change them, and what will a call actually operate on? OpenSCAD is really intuitive and it's easy to understand how to make it create the design I have in mind. I'm thinking it has a lot to do with the declarative style of OpenSCAD vs CQ linear functional style.

**Comment by xix-xeaon** [comment]
Oh, actually, the second `__len__` definition is probably just a copy paste mistake and either shouldn't be there at all, or should refer to something else.

**Comment by jmwright** [comment]
> Yes, I tried CQ through FreeCAD first but we don't really get along.

Can you tell me why that is? Is it just personal preference, or are there things that could be improved about the FreeCAD module?

> However, having tested it for a bit now, I find it very difficult to grasp how CQ actually works and how I can use it to make my designs. 

Three core CQ concepts that might help you are the [stack](http://parametricparts.com/docs/cadquerybasics.html#the-stack), [chaining](http://parametricparts.com/docs/cadquerybasics.html#chaining) and [selectors](http://parametricparts.com/docs/cadquerybasics.html#selectors).

The rest of the basics on that page may help as well. Please feel free to asks questions through issues too.

**Comment by xix-xeaon** [comment]
Just personal preference I guess, I can't think of anything wrong with the module.

I'll have a look and see if I can wrap my head around how CQ works. Thanks!

**Comment by jmwright** [comment]
No problem. Feel free to post an issue about what you're trying to do and ask the community how they would do it.

**Comment by jmwright** [comment]
> Oh, actually, the second __len__ definition is probably just a copy paste mistake and either shouldn't be there at all, or should refer to something else.

I checked into it, and it sounds like the __len__(self, other) definition is a hold-over connected to FreeCAD functionality that we don't tap into. All those self-other function definitions in the same part of the codebase could probably be removed, but I'd like to do some research and experimentation before doing so.

Thanks again for contributing.

**Pull request merged**
