### PR TITLE
fixes docker problem

### PR DESCRIPTION
**Pull request by dcowden**
not working on python2-- and docker hub doesnt run the tests when it builds, so
the builds appear to work but then dont!
this fixes it though-- still need to somehow get dockerhub to run the build and test script, not just the docker image.

### CODE REVIEW

**Comment by dcowden** [comment]
@jmwright @RustyVermeer I'm having problems getting this small patch to pass tests on python 3.6-- its getting a freecad segfault running tests.

I _think_ i remember some conversations around this. I ran it 3 times in a row and its repeatable.  Anyone have ideas? I really doubt my changes actually introduced this problem though i suppose its possible.

**Comment by dcowden** [comment]
I suspect this could be because we're using freecad 0.17 as a part of the python 3.6 build-- that's not stable yet is it?

**Comment by jmwright** [comment]
@dcowden To my knowledge there's not a Python 3 version of 0.16, and probably never will be. 0.17 is not stable yet, but it is in feature freeze. I think that @adam-urbanczyk did something temporary with the version that Anaconda installs on Travis to get rid of the segfaults. Maybe he can point you in the right direction?

**Comment by dcowden** [comment]
@adam-urbanczyk ideas on how to get rid of this segfault?

**Comment by adam-urbanczyk** [comment]
@dcowden I am using this FreeCAD build for CI:
https://anaconda.org/freecad/freecad/0.17/download/linux-64/freecad-0.17-py36_11.tar.bz2

You can install it into a new conda env like this:

`conda create -y -q -n freecad_cq3 -c freecad -c conda-forge freecad=0.17=py36_11 python=3.6 pyparsing conda mock;`

Not sure though how to marry this with docker. Would this help: https://github.com/rothnic/docker-tinyconda ?

**Comment by fragmuffin** [comment]
I've done almost exactly that with docker-builds for virtual environments in `cqparts`.

I wanted an environment that I could use to quickly run unit-tests, and to test library deployment, so I staged it into 3 separate environments: a base environment, then using the base containers built the `unittest` and `deploytest` docker containers for both `ubuntu-py2` and `ubuntu-py3` environments.

The conda command is in: [cqparts/env](https://github.com/fragmuffin/cqparts/tree/master/env) in the `ubuntu-py3/setup.sh` file.

If you'd like me to implement the same strategy in `cadquery`, I'd be happy to create a PR for it... just say the word.

**Comment by dcowden** [comment]
@adam-urbanczyk thanks. The segfault i'm getting isnt in the docker build. Actually, the docker build works fine. its the main build that's failing-- its getting a segfault when it does python runtests.py.

Can you have a look at the most recent failure and see if it looks familiar? Though this PR is about docker, I'm pretty sure its not related to Docker. the only change I made was a change to a python command line file.

**Comment by adam-urbanczyk** [comment]
@dcowden  I think all this was caused by recently changed latest OCCT package version in the conda-forge channel. I fixed the version in #239

**Comment by adam-urbanczyk** [comment]
@dcowden  #239 seems to be passing. In my PR FreeCAD and OCCT versions are fixed to:

`freecad=0.17=py36_11 occt=7.2.0=occt7.2.0_0`

Now I realized that you just pushed a change to travis.yml to use `freecad=0.17=py36_12` Should I update my PR? Or do we leave the current version?

**Comment by dcowden** [comment]
@adam-urbanczyk I dont know-- which one do you think is the best one to use? Is there a reason we might prefer the occt version or the non-occt version? it appears that either your solution or mine will work, but not sure which is best.

**Comment by adam-urbanczyk** [comment]
@dcowden I was not precise. We need to define the OCCT version exactly to avoid this kind of mess in the future. So either:

`freecad=0.17=py36_11 occt=7.2.0=occt7.2.0_0` (my PR)

or

`freecad=0.17=py36_12 occt=7.2.0=2` (what is used implicitly in your PR)

In the latter case, you'd have to still put this explicitly into travis.yml.

**Comment by dcowden** [comment]
thanks @adam-urbanczyk for the help getting the segfault fixed!

**Pull request merged**
