### PR TITLE
cadquery.Plane equality

### PR DESCRIPTION
**Pull request by fragmuffin**
Test equality (or inequality) of 2 `cadquery.Plane` instances.
effectively: do they coincide?

```python
>>> import cadquery
>>> p1 = cadquery.Plane(origin=(1,2,3), xDir=(10,5,0), normal=(0,0,4))
>>> p2 = cadquery.Plane(origin=(1,2,3), xDir=(1,0.5,0), normal=(0,0,2))
>>> p1 == p2
True
```

### CODE REVIEW

**Comment by jmwright** [comment]
@dcowden This looks good to me. Do you want me to merge?

**Comment by dcowden** [comment]
Yes I had a look too, it looked good to me. Please merge, I'm on the road
atm

**Comment by jmwright** [comment]
@fragmuffin Thanks for the contribution!

**Comment by fragmuffin** [comment]
My pleasure @jmwright

**Pull request merged**
