### PR TITLE
allow empty results

### PR DESCRIPTION
**Pull request by dcowden**
@jmwright this should allow empty build results

### CODE REVIEW

**Comment by jmwright** [comment]
Thanks. I now get the following error.

```python
list index out of range
```

**Comment by jmwright** [comment]
Looks like the error is in [this line](https://github.com/dcowden/cadquery/blob/empty_result/cadquery/cqgi.py#L172) and happens when I'm only using debug().

**Comment by dcowden** [comment]
@jmwright  sorry about that, i forgot that i try to grab the first result.

This is a fixed version-- be aware that the first_result property could now be None, where before it would always have a value.

**Comment by jmwright** [comment]
Works well now, thanks. Here's a little preview. I've got the visibility toggled on the primary object so that all you see is the debug object. By default the debug objects are rendered in red with  0.8 alpha, and they're labelled in the model tree with the prefix "Debug".

screenshot_2017-09-11_21-33-55

**Comment by dcowden** [comment]
@jmwright very nice!!!

**Pull request merged**
