### PR TITLE
First steps towards fixing CQGI Python 3 compatibility.

### PR DESCRIPTION
**Pull request by jmwright**
WIP: Please do not merge yet. I'm putting this out there to communicate what I'm doing, run the full sets of tests against my code, and allow @dcowden and @adam-urbanczyk to make comments as these fixes progress. These errors are down in the AST parts of the code, and there seem to be some subtle things going on, so it's taking me awhile to straighten things out.

### CODE REVIEW

**Comment by jmwright** [comment]
@adam-urbanczyk @dcowden This is ready to be checked over. If you approve of the way I fixed the failures, we should be able to merge this to get our builds passing again.

**Comment by adam-urbanczyk** [comment]
@jmwright  to me it looks OK, but I have to admit I do not understand cqgi implementation fully.

**Comment by dcowden** [comment]
@jmwright this looks ok as long as the tests pass..

@adam-urbanczyk cqgi the goal of cqgi is to provide a common way for tools to execute cqgi scripts, in a way that scripts don't need to be modified to suit the tool, and so that its easy for scripts to 'just work' without a lot of work by the script developer

In very short, CQGI does these steps:

* parse the script, check it for syntax errors
* make an AST tree of the script, and using that tree:
    * find variables that are set to contants, and tabulate their names and types
* return a structure to the calling environment, allowing it to set variables to new values
* when the calling environment runs the script, we run the script in a secure sandbox that doesnt allow nasty other builtins:
   * inject the show_object() method so that it can be called by the script   
   * replace the vars with the new values, and capture the output objects
   * run the script
   * capture the output and give it back to the calling environment

You can read more [here ](http://dcowden.github.io/cadquery/_modules/cadquery/cqgi.html)

**Comment by adam-urbanczyk** [comment]
@dcowden  thanks!

BTW I think #203 can be closed.

**Pull request merged**
